#%RAML 1.0
title: upstreamAPI
version: v1
baseUri: http://localhost:3000
/dayOfWeek:
  /{id}:
    get:
      description: Returns the name of the day when given a number
      responses:
        200:
          body:
            text/xml:
              example: <?xml version="1.0" encoding="UTF-8"?>
                       <dayOfWeek>Saturday</dayOfWeek>
        400:
          body:
            text/xml:
              example: <?xml version="1.0" encoding="UTF-8"?>
                       <error>Invalid day of the week</error>
/monthOfYear:
  /{id}:
    get:
      description: Returns name of the month when given a number
      responses:
        200:
          body:
            text/xml:
              example: <?xml version="1.0" encoding="UTF-8"?>
                       <monthOfYear>July</monthOfYear>
        400:
          body:
            text/xml:
              example: <?xml version="1.0" encoding="UTF-8"?>
                       <error>Invalid month of the year</error>